name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.23

    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Lint
      run: earthly +lint

    - name: Test
      run: earthly +test